<?php

echo "<link rel=stylesheet type=text/css href=Style.css>";

/*Establishes connection to database*/
include("connectToDatabase.php");
session_start();


// Current user name is got through the Session
$currentUser=$_SESSION["session1"];

//calculate total price of the user
$selectTotalPriceQuery = "select SUM(productPrice*productQty) as 'totalPrice' from sales where salesId=''";
$executeTotalPriceQuery = mysqli_query($con,$selectTotalPriceQuery);
$rowTotalPrice = mysqli_fetch_array($executeTotalPriceQuery);

//Getting the total price (current order) in a variable
$totalPrice = $rowTotalPrice['totalPrice'];


//Update current username and totalPrice to final (orders) table
//When inserted, the salesId is autogenerated (auto incremented) in orders table
$updateOrdersQuery = "insert into orders(username,totalPrice,currentCheckout) values('$currentUser','$totalPrice','YES')";
$executeUpdateOrdersQuery = mysqli_query($con,$updateOrdersQuery);

// Now order code has been generated and the total price is ready

// currentCheckout "YES" is the proceeding checkout. Everything else will have "NO"
// This is just to identify Current Sales id
$getSalesIdQuery = "select salesId from orders where currentCheckout='YES'";
$executeGetSalesIdQuery = mysqli_query($con,$getSalesIdQuery);

// Get the salesId in a temporary variable
$rowCurrentSalesId = mysqli_fetch_array($executeGetSalesIdQuery);
$currentSalesId = $rowCurrentSalesId['salesId']; // This holds the current sales id

// If total price is 0, that means 
// user has pressed Checkout without purchasing anything
// Redirect

if($totalPrice==0){
	//Delete the current salesId
	$deleteOrderQuery = "delete from orders where salesId='$currentSalesId'";
	$executeDeleteOrderQuery = mysqli_query($con,$deleteOrderQuery);
	$rowDeleteOrder = mysqli_fetch_array($executeDeleteOrderQuery);
	header("Location:noItemsToCheckout.php");
}else
{

// Should update the order code in sales table, where salesId is blank
$updateSalesIdQuery = "update sales set salesId='$currentSalesId' where salesId=''";
$executeUpdateSalesQuery = mysqli_query($con,$updateSalesIdQuery);

// Should change the currentCheckout to "NO"
$revertCurrentCheckoutQuery = "update orders set currentCheckout='NO' where currentCheckout='YES'";
$executeRevertCurrentCheckoutQuery = mysqli_query($con,$revertCurrentCheckoutQuery); 


// Finalise and update the new available quantity of products, since checkout have been made
// Read data from productsDummy, and update to products
$selectDummyTableQuery = "select productId,availableQty from productsDummy";
$resultsDummyTableQuery = mysqli_query($con,$selectDummyTableQuery);

while($row = mysqli_fetch_array($resultsDummyTableQuery))
{

	$productId = $row['productId'];
	$availableQty = $row['availableQty'];

	$updateProducts = "update products set availableQty='$availableQty' where productId='$productId'";
	$executeUpdateProductsQuery = mysqli_query($con,$updateProducts);

}


header("Location:salesDetails.php");
}//else ends

// CLosing the connection
//mysqli_close($con);


?>